# **Numpy**

In [2]:
import numpy as np

### **Vectores con Numpy**

In [6]:
# Estructuras de ejemplo
vector_1 = np.array([23, -4, 5])
vec_2 = [12, 3, -12]
vector_2 = np.array(vec_2)

##### **Sumas, restas y producto por un escalar (número)**

In [10]:
# Se hace la operación tal cual

#Suma
vec_suma = vector_1 + vector_2
print(vec_suma)

#Resta
vec_resta = vector_1 - vector_2
print(vec_resta)

#Producto por escalar
vec_escalar = vector_1 * vector_2
print(vec_escalar)


[35 -1 -7]
[11 -7 17]
[276 -12 -60]


##### **Producto escalar (dot)**

In [18]:
#1 
dot_prod = np.dot(vector_1, vector_2)

#2
dot_prod_2 = vector_1.dot(vector_2)

#--------------#
print(dot_prod_1, dot_prod_2)



204 204


##### **Norma, Longitud o Magnitud**

In [16]:
norm_1 = np.linalg.norm(vector_1)
norm_2 = np.linalg.norm(vector_2)

print(norm_1, norm_2)

23.874672772626646 17.233687939614086


##### **Coseno del ángulo**

In [20]:

cos_ang_1_2 = dot_prod/(norm_1 * norm_2)     #-----> Reutilizando las variables anteriores

cos_ang = np.dot(vector_1, vector_2) / (np.linalg.norm(vector_1) * np.linalg.norm(vector_2)) #--> Sin reutilizar

print(cos_ang_1_2, cos_ang)


0.49580912449444803 0.49580912449444803


##### **Distancia entre 2 vectores**

In [21]:
dist_1_2 = np.linalg.norm(vector_1 - vector_2)

print(dist_1_2)

21.42428528562855


### **Matrices con Numpy**

##### **Transformar matriz a array**

In [7]:
# Matriz con listas
matriz = [[1,2,4],
          [3,5,6]]

import numpy as np

matriz_np = np.array(matriz)
#--------------------------#
A = np.array([[1,3,4],
              [1,0,0],
              [1,2,2]])

B = np.array([[1,0,5],
              [7,5,0],
              [2,1,1]])

print(type(matriz_np), matriz_np)

<class 'numpy.ndarray'> [[1 2 4]
 [3 5 6]]


##### **Producto por un escalar (número), sumas, restas y producto matricial (entre 2 matrices)**

In [13]:
#Producto por escalar:
producto_por_escalar = 3 * A

print("Producto por escalar, 3 * A: \n", producto_por_escalar)

#Suma:
suma = A + B

print("Suma, A + B:\n", suma)

#Resta:
resta = A - B

print("Resta, A - B:\n", resta)

#Producto matricial:
producto_matricial = A.dot(B)

print("Producto matricial, A x B:\n", producto_matricial)

Producto por escalar, 3 * A: 
 [[ 3  9 12]
 [ 3  0  0]
 [ 3  6  6]]
Suma, A + B:
 [[2 3 9]
 [8 5 0]
 [3 3 3]]
Resta, A - B:
 [[ 0  3 -1]
 [-6 -5  0]
 [-1  1  1]]
Producto matricial, A x B:
 [[30 19  9]
 [ 1  0  5]
 [19 12  7]]


##### **Transposicion de filas a columnas**

In [15]:
A_transpuesta = A.T

print("A:", A,"\n","\n", "At:", A_transpuesta)


A: [[1 3 4]
 [1 0 0]
 [1 2 2]] 
 
 At: [[1 1 1]
 [3 0 2]
 [4 0 2]]


### **Matrices predeterminadas**

##### **Matriz identidad**

In [4]:
# 1s en la diagonal principal
I = np.identity(3)

print(I)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]


##### **Matriz de 0s**

In [8]:
matriz_zeros = np.zeros((3,4))  #---> doble parentesis porque es una tupla
print(matriz_zeros)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


##### **Matriz de 1s**

In [11]:
matriz_unos = np.ones((4,5))
print(matriz_unos)   #----> es un float de Numpy, para pasalo a INT --> matriz_unos = np.ones((4,5),np.int32)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


##### **Matriz de cualquier número**

In [13]:
matriz_num = np.full((3,2),50) #---> En el segundo argumento va el número del que sea la matriz
print(matriz_num)

[[50 50]
 [50 50]
 [50 50]]


##### **Secuencias**

In [19]:
sec_0_10 = np.arange(11)
print(sec_0_10)
#--------------------#
sec_pares = np.arange(0, 11, 2) #-------> Para que el salto sea de 2 en 2
print(sec_pares)
#--------------------#
#Especificar el tipo de dato:
sec_float = np.arange(0, 21, 2, np.float64)
print(sec_float)

[ 0  1  2  3  4  5  6  7  8  9 10]
[ 0  2  4  6  8 10]
[ 0.  2.  4.  6.  8. 10. 12. 14. 16. 18. 20.]


##### **Indexing multidimensional**

In [9]:
array_multi = np.array([[1,2,3,4,5], [6,7,8,9,10], [11,12,13,14,15]])
print(array_multi)

print("2 primeras filas y 3 primeras columnas\n", array_multi[:2, :3])

print("Todas las filas, cada dos columnas\n", array_multi[:, ::2])

print("Invertir las filas\n", array_multi[:, ::-1])

print("Invertir columnas\n", array_multi[::-1, :])

print("Invertir todo\n", array_multi[::-1, ::-1,])

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]]
2 primeras filas y 3 primeras columnas
 [[1 2 3]
 [6 7 8]]
Todas las filas, cada dos columnas
 [[ 1  3  5]
 [ 6  8 10]
 [11 13 15]]
Invertir las filas
 [[ 5  4  3  2  1]
 [10  9  8  7  6]
 [15 14 13 12 11]]
Invertir columnas
 [[11 12 13 14 15]
 [ 6  7  8  9 10]
 [ 1  2  3  4  5]]
Invertir todo
 [[15 14 13 12 11]
 [10  9  8  7  6]
 [ 5  4  3  2  1]]


##### **Sub array**

In [5]:
x = np.array([2,4,5,2,3,7,2])
x_bools = np.array(x == 2)
print(x_bools)
sub_x = x[x_bools]
print(sub_x)

[ True False False  True False False  True]
[2 2 2]


##### **Reshape**

In [6]:
x = np.arange(9)
print(x)
y = x.reshape(3,3)
print(y)

[0 1 2 3 4 5 6 7 8]
[[0 1 2]
 [3 4 5]
 [6 7 8]]


### **Random**

In [32]:
#Secuencia random = 
print(np.random.rand(5))
print("---------------------------------------------------------")
#Matriz random = 
matriz_random = np.random.rand(3,4)
print(matriz_random)
print("---------------------------------------------------------")
#Matriz random números enteros
matriz_rand_enteros = np.random.randint(0, 20, size = (2, 3)) #-------> los dos primeros args (0, 20) son el rango de aleatoriedad
print(matriz_rand_enteros)                                    #-------> Para el tamaño de la matriz se usa size = (x, y)
print("---------------------------------------------------------")                                                            #-------> Para secuencia unidimensional size = (x)

[0.29624487 0.2244638  0.14976368 0.03107059 0.09351753]
---------------------------------------------------------
[[0.43645615 0.58568625 0.78631733 0.81383886]
 [0.81660236 0.92467507 0.69839266 0.1388494 ]
 [0.81459016 0.92439933 0.46364716 0.72255466]]
---------------------------------------------------------
[[ 3 11 13]
 [19  9  4]]
---------------------------------------------------------


#### **Seed**

Para que al usar random, ese primer output se guarde para las siguientes funciones

In [55]:
np.random.seed(1234)
print(np.random.rand(4))
print(np.random.randint(5))
print(np.random.randint(2, 10))

[0.19151945 0.62210877 0.43772774 0.78535858]
1
9
