# **Numpy**

In [1]:
import numpy as np

### **Vectores con Numpy**

In [6]:
# Estructuras de ejemplo
vector_1 = np.array([23, -4, 5])
vec_2 = [12, 3, -12]
vector_2 = np.array(vec_2)

##### **Sumas, restas y producto por un escalar (número)**

In [10]:
# Se hace la operación tal cual

#Suma
vec_suma = vector_1 + vector_2
print(vec_suma)

#Resta
vec_resta = vector_1 - vector_2
print(vec_resta)

#Producto por escalar
vec_escalar = vector_1 * vector_2
print(vec_escalar)


[35 -1 -7]
[11 -7 17]
[276 -12 -60]


##### **Producto escalar (dot)**

In [18]:
#1 
dot_prod = np.dot(vector_1, vector_2)

#2
dot_prod_2 = vector_1.dot(vector_2)

#--------------#
print(dot_prod_1, dot_prod_2)



204 204


##### **Norma, Longitud o Magnitud**

In [16]:
norm_1 = np.linalg.norm(vector_1)
norm_2 = np.linalg.norm(vector_2)

print(norm_1, norm_2)

23.874672772626646 17.233687939614086


##### **Coseno del ángulo**

In [20]:

cos_ang_1_2 = dot_prod/(norm_1 * norm_2)     #-----> Reutilizando las variables anteriores

cos_ang = np.dot(vector_1, vector_2) / (np.linalg.norm(vector_1) * np.linalg.norm(vector_2)) #--> Sin reutilizar

print(cos_ang_1_2, cos_ang)


0.49580912449444803 0.49580912449444803


##### **Distancia entre 2 vectores**

In [21]:
dist_1_2 = np.linalg.norm(vector_1 - vector_2)

print(dist_1_2)

21.42428528562855


### **Matrices con Numpy**

##### **Transformar matriz a array**

In [7]:
# Matriz con listas
matriz = [[1,2,4],
          [3,5,6]]

import numpy as np

matriz_np = np.array(matriz)
#--------------------------#
A = np.array([[1,3,4],
              [1,0,0],
              [1,2,2]])

B = np.array([[1,0,5],
              [7,5,0],
              [2,1,1]])

print(type(matriz_np), matriz_np)

<class 'numpy.ndarray'> [[1 2 4]
 [3 5 6]]


##### **Producto por un escalar (número), sumas, restas y producto matricial (entre 2 matrices)**

In [13]:
#Producto por escalar:
producto_por_escalar = 3 * A

print("Producto por escalar, 3 * A: \n", producto_por_escalar)

#Suma:
suma = A + B

print("Suma, A + B:\n", suma)

#Resta:
resta = A - B

print("Resta, A - B:\n", resta)

#Producto matricial:
producto_matricial = A.dot(B)

print("Producto matricial, A x B:\n", producto_matricial)

Producto por escalar, 3 * A: 
 [[ 3  9 12]
 [ 3  0  0]
 [ 3  6  6]]
Suma, A + B:
 [[2 3 9]
 [8 5 0]
 [3 3 3]]
Resta, A - B:
 [[ 0  3 -1]
 [-6 -5  0]
 [-1  1  1]]
Producto matricial, A x B:
 [[30 19  9]
 [ 1  0  5]
 [19 12  7]]


##### **Transposicion de filas a columnas**

In [15]:
A_transpuesta = A.T

print("A:", A,"\n","\n", "At:", A_transpuesta)


A: [[1 3 4]
 [1 0 0]
 [1 2 2]] 
 
 At: [[1 1 1]
 [3 0 2]
 [4 0 2]]
